// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:matrix_app/core/user_model/user_model.dart';
import 'package:matrix_app/features/cart/cart_model/cart_item_model.dart';
import 'package:matrix_app/features/cart/cart_model/cart_model.dart';
import 'package:matrix_app/features/home/model_prodect/product_model.dart';
import 'package:matrix_app/features/home/model_prodect/product_specs.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(CartModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(ProductSpecsAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(CartModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(ProductSpecsAdapter());
    registerAdapter(UserModelAdapter());
  }
}
